#!/bin/csh
##
## Purpose: get daily CODE ZTD-file from AIUB
##
## Originally written by Feng Zhou on 05/09/2017 @ GFZ
##
## Email: zhouforme@163.com
##
## Section 1.1, Geodesy, GFZ German Research Centre for Geosciences
#
##===============================BEGIN PROGRAM=====================================##
if ($#argv < 2) then
more << EOF

   Usage $0 <yyyy> <doy> [ndays]

   EXAMPLES: $0 2017 001
             $0 2017 001 10

EOF
   exit
endif

@ yyyy  = $1
@ doy   = $2
@ count = 1
if ($#argv >= 3) then
   @ count = $3
endif

set ztddir = /Users/zhoufeng/Documents/GNSS_download/cod_ztd
if (! -d ${ztddir}) /bin/mkdir -p ${ztddir}
cd ${ztddir}

echo " "
echo " Downloading CODE ZTD files from ftp://ftp.aiub.unibe.ch ..."
echo " "

while (${count})
   set cdoy = `echo $doy | awk '{printf("%3.3d\n",$1)}'`
   echo " Year:" ${yyyy} " DOY:" ${cdoy}

   set WEEKD = `mjday $doy $yyyy | awk '{nwk=int(($1-44244)/7);nwkd=$1-44244-nwk*7;print nwk*10+nwkd}'`
   
   wget -qr -nH --cut-dirs=2 ftp://ftp.aiub.unibe.ch/CODE/${yyyy}/COD${WEEKD}.TRO.Z

   sh_uncompress COD${WEEKD}.TRO.Z

   @ count --
   @ doy ++
end
#
##================================END PROGRAM======================================##
